In [152]:
import pandas as pd
data = pd.read_csv('test_data.csv', sep=' -> ', engine='python', header=None)

def find_lines_loc(data):
    x1y1 = (
        data[0]
        .str
        .split(',',expand=True)
        .rename(columns={0:'x1', 1:'y1'})
    )
    x2y2 = (
        data[1]
        .str
        .split(',',expand=True)
        .rename(columns={0:'x2', 1:'y2'})
    )
    data = pd.concat([x1y1,x2y2], axis=1).astype('int32')
    range_vals = range(int(data.values.max())+1)

    diagram = pd.DataFrame(0, index=range_vals, columns=range_vals)

    for idx in range(len(data)):

        x1 = data.iloc[idx].x1
        y1 = data.iloc[idx].y1
        x2 = data.iloc[idx].x2
        y2 = data.iloc[idx].y2
        # print(x1,y1,x2,y2)
        if y1 == y2:
            if x1 > x2:
                diagram.loc[y1,x2:x1] = diagram.loc[y1,x2:x1] + 1
            else:
                diagram.loc[y1,x1:x2] = diagram.loc[y1,x1:x2] + 1

        if x1 == x2:
            if y1 > y2:
                diagram.loc[y2:y1,x1] = diagram.loc[y2:y1,x1] + 1
            else:
                diagram.loc[y1:y2,x1] = diagram.loc[y1:y2,x1] + 1

    twos = diagram >= 2
    print(diagram)
    print(f'Total no twos: {twos.values.sum()}')

find_lines_loc(data)

   0  1  2  3  4  5  6  7  8  9
0  0  0  0  0  0  0  0  1  0  0
1  0  0  1  0  0  0  0  1  0  0
2  0  0  1  0  0  0  0  1  0  0
3  0  0  0  0  0  0  0  1  0  0
4  0  1  1  2  1  1  1  2  1  1
5  0  0  0  0  0  0  0  0  0  0
6  0  0  0  0  0  0  0  0  0  0
7  0  0  0  0  0  0  0  0  0  0
8  0  0  0  0  0  0  0  0  0  0
9  2  2  2  1  1  1  0  0  0  0
Total no twos: 5

In [153]:
import pandas as pd
data = pd.read_csv('input_data.csv', sep=' -> ', engine='python', header=None)
find_lines_loc(data)

     0    1    2    3    4    5    6    7    8    9    ...  981  982  983  \
0      0    0    0    0    0    0    0    0    0    0  ...    0    0    0
1      0    0    0    0    0    0    0    0    0    0  ...    0    0    0
2      0    0    0    0    0    0    0    0    0    0  ...    0    0    0
3      0    0    0    0    0    0    0    0    0    0  ...    0    0    0
4      0    0    0    0    0    0    0    0    0    0  ...    0    0    0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
986    0    0    0    0    0    0    0    0    0    0  ...    0    0    0
987    0    0    0    0    0    0    0    0    0    0  ...    0    0    0
988    0    0    0    0    0    0    0    0    0    0  ...    0    0    0
989    0    0    0    0    0    0    0    0    0    0  ...    0    0    0
990    0    0    0    0    0    0    0    0    0    0  ...    0    0    0

     984  985  986  987  988  989  990
0      0    0    0    0    0    0    0
1      0    0    0    0    0    0    0
2      0    0    0    0    0    0    0
3      0    0    0    0    0    0    0
4      0    0    0    0    0    0    0
..   ...  ...  ...  ...  ...  ...  ...
986    0    0    0    0    0    0    0
987    0    0    0    0    0    0    0
988    0    0    0    0    0    0    0
989    0    0    0    0    0    0    0
990    0    0    0    0    0    0    0

[991 rows x 991 columns]
Total no twos: 6225

In [161]:
import pandas as pd
data = pd.read_csv('test_data.csv', sep=' -> ', engine='python', header=None)

def find_vents(data, flag:bool):

    from skimage.draw import line

    x1y1 = (
        data[0]
        .str
        .split(',',expand=True)
        .rename(columns={0:'x1', 1:'y1'})
    )
    x2y2 = (
        data[1]
        .str
        .split(',',expand=True)
        .rename(columns={0:'x2', 1:'y2'})
    )
    data = pd.concat([x1y1,x2y2], axis=1).astype('int32')
    range_vals = range(int(data.values.max())+1)

    diagram = pd.DataFrame(0, index=range_vals, columns=range_vals).to_numpy()

    for idx in range(len(data)):

        x1 = data.iloc[idx].x1
        y1 = data.iloc[idx].y1
        x2 = data.iloc[idx].x2
        y2 = data.iloc[idx].y2

        if flag:
            rr,cc = line(y1,x1,y2,x2)
            diagram[rr,cc] = diagram[rr,cc] + 1

        else:
            if x1 == x2 or y1 == y2:
                rr,cc = line(y1,x1,y2,x2)
                diagram[rr,cc] = diagram[rr,cc] + 1

    twos = diagram >= 2
    print(f'Total no twos: {twos.sum()}')
    return(pd.DataFrame(diagram))

find_vents(data, False)

Total no twos: 5

   0  1  2  3  4  5  6  7  8  9
0  0  0  0  0  0  0  0  1  0  0
1  0  0  1  0  0  0  0  1  0  0
2  0  0  1  0  0  0  0  1  0  0
3  0  0  0  0  0  0  0  1  0  0
4  0  1  1  2  1  1  1  2  1  1
5  0  0  0  0  0  0  0  0  0  0
6  0  0  0  0  0  0  0  0  0  0
7  0  0  0  0  0  0  0  0  0  0
8  0  0  0  0  0  0  0  0  0  0
9  2  2  2  1  1  1  0  0  0  0

In [162]:
import pandas as pd

data = pd.read_csv('input_data.csv', sep=' -> ', engine='python', header=None)
find_vents(data, True)

Total no twos: 22116

,0,1,2,3,4,5,6,7,8,9,...,981,982,983,984,985,986,987,988,989,990
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
986,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
987,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
988,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
989,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
990,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0